### ISSUE TITLE
could not mount /data and unable to find crypto footer

### ISSUE THREAD

**Issue by Saiv46** [TeamWin/android_device_samsung_s3ve3g#1]
TWRP version: 3.3.1-1
OS: LineageOS 16.0 (Oreo)
Magisk installed
Full device encryption

The title says by itself - I cannot decrypt /data so cannot use backups or anything

**Comment by aIecxs** [comment]
please tell any samsung device where you got the idea from TWRP will support samsung encryption ;)

**Comment by Saiv46** [comment]
Sorry for not closing this issue earier.

I was used old versions of TWRP and it worked as expected.
